version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres12_wallet
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_wallet
    networks:
      wallet_network:
        aliases:
          - wallet.database.loc
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_wallet
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_wallet?sslmode=disable
    depends_on:
      - postgres    
    command: [ "/app/main" ]
    networks:
      wallet_network:
        aliases:
          - wallet.app.loc
  gomock:
    build:
      context: .
      dockerfile: .docker/gomock/Dockerfile
    container_name: gomock_wallet
networks:
  wallet_network: